# 數組的創建和訪問

In [9]:
import numpy as np

In [10]:
# create from python list
list_1 = [1, 2, 3, 4]

In [11]:
list_1

[1, 2, 3, 4]

In [12]:
array_1 = np.array(list_1)

In [13]:
array_1

array([1, 2, 3, 4])

In [14]:
list_2 = [5, 6, 7, 8]

In [15]:
array_2 = np.array([list_1, list_2])

In [16]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
array_2.shape

(2, 4)

In [25]:
array_2.size

8

In [26]:
array_2.dtype

dtype('int32')

In [29]:
array_3 = np.array([[1.0, 2, 3], [4.0, 5, 6]])

In [30]:
array_3.dtype

dtype('float64')

In [31]:
array_3.shape

(2, 3)

In [34]:
array_4 = np.arange(1, 10, 2)

In [35]:
array_4

array([1, 3, 5, 7, 9])

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 以上都是Float 

In [42]:
np.eye(5).dtype

dtype('float64')

In [43]:
a = np.arange(1, 10)

In [44]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[0]

1

In [45]:
a[1]

2

In [47]:
a[1:5]

array([2, 3, 4, 5])

# 包頭唔包尾

In [48]:
a[5:8]

array([6, 7, 8])

In [49]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
b[1][0]

4

# 第1行 第0個

In [53]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [54]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
c[:2, 1:]

array([[2, 3],
       [5, 6]])

# 切片 : 0軸 -> 拎0到1行, 1軸 -> 拎1列到尾列